# Generated by Django 6.0.6 on 2026-06-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_result_comment_result_penalty_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('new_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('comment', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='competitions.result')),
            ],
        ),
    ]
