# Generated by Django 6.0.6 on 2026-06-11 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_resultlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='has_individual',
            field=models.BooleanField(default=True, verbose_name='Проводить личный зачет'),
        ),
        migrations.AddField(
            model_name='competition',
            name='has_team',
            field=models.BooleanField(default=False, verbose_name='Проводить командный зачет'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(default='Активно', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название соревнования'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.competitiontype', verbose_name='Тип'),
        ),
    ]
