# Generated by Django 6.0.6 on 2026-06-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competition_has_individual_competition_has_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='bib_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Стартовый номер'),
        ),
    ]
