# Generated by Django 6.0.6 on 2026-06-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_participant_bib_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
