# Generated by Django 6.0.6 on 2026-06-12 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.competition', verbose_name='Соревнование'),
        ),
    ]
