# Generated by Django 6.0.6 on 2026-06-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_auditlog_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetype',
            name='is_lower_better',
            field=models.BooleanField(default=True, verbose_name='Меньшее значение побеждает (например, время в секундах)'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('Активно', 'Активно'), ('Завершено', 'Завершено'), ('Черновик', 'Черновик')], default='Активно', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='result',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='competitions.participant'),
        ),
        migrations.AlterField(
            model_name='result',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='competitions.stage'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('Организатор', 'Организатор'), ('Главный судья', 'Главный судья'), ('Судья', 'Судья')], max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('competition', 'bib_number'), name='unique_bib_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'participant'), name='unique_team_member'),
        ),
    ]
