# Generated by Django 6.0.6 on 2026-06-14 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_result_unique_result_per_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='chief_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_competitions', to=settings.AUTH_USER_MODEL, verbose_name='Главный судья соревнований'),
        ),
    ]
