# Generated by Django 6.0.6 on 2026-06-14 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_competition_chief_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='assigned_stages', to=settings.AUTH_USER_MODEL, verbose_name='Назначенные судьи'),
        ),
    ]
