# Generated by Django 6.0.6 on 2026-06-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_stage_judges'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='scoring_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройки алгоритма (JSON)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='scoring_method',
            field=models.CharField(choices=[('crossfit', 'Очки за места (CrossFit - 100, 95, 90...)'), ('normalization', 'Линейная нормализация (Баллы 0-100)'), ('multiplier', 'Кастомный множитель (Своя цена за единицу)'), ('iaaf', 'Официальная формула IAAF (Многоборье)'), ('fina', 'Очки FINA (Плавание)')], default='normalization', max_length=50, verbose_name='Алгоритм подсчета баллов'),
        ),
    ]
