# Generated by Django 6.0.6 on 2026-06-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_stage_scoring_config_stage_scoring_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Собственный вес (кг)'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='scoring_method',
            field=models.CharField(choices=[('crossfit', 'Очки за места (CrossFit - 100, 95, 90...)'), ('normalization', 'Линейная нормализация (Баллы 0-100)'), ('multiplier', 'Кастомный множитель (Своя цена за единицу)'), ('iaaf', 'Официальная формула IAAF (Многоборье)'), ('fina', 'Очки FINA (Плавание)'), ('sinclair', 'Коэффициент Синклера (Тяжелая атлетика)')], default='normalization', max_length=50, verbose_name='Алгоритм подсчета баллов'),
        ),
    ]
